### ISSUE TITLE
can not load web font correctly that is indicated in css

### ISSUE THREAD

**Issue by polaris-zx** [meenie/munee#79]
```css
@font-face {
    font-family: 'Source Sans Pro';
    font-style: normal;
    font-weight: 300;
    src: local('Source Sans Pro Light'), local('SourceSansPro-Light'), url('../fonts/toadOcfmlt9b38dHJxOBGOode0-EuMkY--TSyExeINg.woff2') format('woff2'), url('../fonts/toadOcfmlt9b38dHJxOBGNbE_oMaV8t2eFeISPpzbdE.woff') format('woff');
}
```
i can not load the font.
